name = "bondvault"
compatibility_date = "2025-10-01"
main = ".open-next/worker.js"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "bondvault-production"
database_id = "990a8dc7-af95-417b-b970-aee4cfb3e72b"

[[kv_namespaces]]
binding = "KV"
id = "9c8d4227f86649ab8bc2b6ab968bcc24"

[[r2_buckets]]
binding = "R2"
bucket_name = "bondvault-assets"

[[queues.producers]]
queue = "match-generation"
binding = "MATCH_QUEUE"

[[queues.producers]]
queue = "notification-delivery"
binding = "NOTIFICATION_QUEUE"

[[queues.producers]]
queue = "cleanup-jobs"
binding = "CLEANUP_QUEUE"

[[queues.producers]]
queue = "draw-processing"
binding = "DRAW_QUEUE"

[[queues.consumers]]
queue = "match-generation"

[[queues.consumers]]
queue = "notification-delivery"

[[queues.consumers]]
queue = "cleanup-jobs"

[[queues.consumers]]
queue = "draw-processing"

[vars]
ENVIRONMENT = "production"
