name = "bondvault-cron"
compatibility_date = "2025-10-01"
main = "index.ts"

compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "bondvault-production-v2"
database_id = "2fc28994-8da8-4bfd-aa55-aeaf5b54701e"

[triggers]
crons = ["0 0 * * *"]
